# SPDX-License-Identifier: EUPL-1.2
# Copyright (c) 2025 Oliver Andrich

version: 2
project_name: gohatch

builds:
  - main: ./cmd/gohatch
    binary: gohatch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: darwin
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: Features
      regexp: '^feat'
    - title: Bug Fixes
      regexp: '^fix'
    - title: Others
      order: 999

homebrew_casks:
  - name: gohatch
    homepage: https://codeberg.org/oliverandrich/gohatch
    description: A project scaffolding tool for Go
    binaries:
      - gohatch
    directory: Casks
    repository:
      git:
        url: "ssh://git@codeberg.org/oliverandrich/homebrew-tap.git"
        private_key: "{{ .Env.CODEBERG_SSH_KEY }}"
    commit_author:
      name: Oliver Andrich
      email: oliver@andrich.me
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gohatch"]
          end

release:
  gitea:
    owner: oliverandrich
    name: gohatch
  draft: false
  prerelease: auto

gitea_urls:
  api: https://codeberg.org/api/v1
  download: https://codeberg.org
