# SPDX-License-Identifier: EUPL-1.2
# Copyright (c) 2025 Oliver Andrich

when:
  event: tag

steps:
  - name: test
    image: golang:1.24
    commands:
      - go test -race ./...

  - name: release
    image: goreleaser/goreleaser:latest
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
      CODEBERG_SSH_KEY:
        from_secret: codeberg_ssh_key
      GORELEASER_FORCE_TOKEN: gitea
    commands:
      - goreleaser release --clean
